services:
  - type: web
    name: kln-ayurveda-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
